### ISSUE TITLE
gulp报错  Error: less version 3.9.0 is not currently supported

### ISSUE THREAD

**Issue by ackurdeeve** [shenliyang/hexo-theme-snippet#102]
\node_modules\accord\lib\index.js:29
      throw new Error(name + " version " + version + " is not currently supported");
      ^

Error: less version 3.9.0 is not currently supported
    at Object.exports.load (J:\Myweb\ackurdeeve.github.io\node_modules\accord\lib\index.js:29:13)
    at Object.<anonymous> (J:\Myweb\ackurdeeve.github.io\node_modules\gulp-less\index.js:9:29)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at J:\Myweb\ackurdeeve.github.io\themes\hexo-theme-snippet\gulpfile.js:4:16

**Comment by shenliyang** [comment]
您好，未发现gulp-less有 version 3.9.0 详见：[gulp-less - npm](https://www.npmjs.com/package/gulp-less)
> 如果有二次开发需求，建议使用主题内的package.json安装依赖。
