### ISSUE TITLE
article.ejs

### ISSUE THREAD

**Issue by ciey** [shenliyang/hexo-theme-snippet#14]
page.ejs内容
`<%- partial('_partial/article', {post: page, index: false}) %>`
而_partial/下缺少article.ejs导致无法生成页面。

**Comment by shenliyang** [comment]
page.ejs 还在完善中，感谢你的反馈

**Comment by yanbinghu** [comment]
请问一下，这个问题怎么解决呢？clone新的主题下来，每次生成都会有这个报错。

**Comment by shenliyang** [comment]
@yanbinghu 您好，请提供一下hexo版本，和相关报错的截图等其他信息。

**Comment by yanbinghu** [comment]
报错信息如下：
```
Unhandled rejection TypeError: /home/hyb/workspaces/hexo/themes/snippet/layout/page.ejs:29
    27|     </article>
    28|     <% } else{ %>
 >> 29|     <%- partial('_partial/article', {post: page, index: false}) %>
    30|     <%}%>
    31| </div>

src.indexOf is not a function
    at Hexo.<anonymous> (/home/hyb/workspaces/hexo/node_modules/hexo-math/bin/index.js:48:19)
    at Filter.execSync (/home/hyb/workspaces/hexo/node_modules/hexo/lib/extend/filter.js:88:25)
    at Hexo.execFilterSync (/home/hyb/workspaces/hexo/node_modules/hexo/lib/hexo/index.js:438:29)
    at Theme._View.View._compiledSync (/home/hyb/workspaces/hexo/node_modules/hexo/lib/theme/view.js:123:33)
    at Theme._View.View.View.renderSync (/home/hyb/workspaces/hexo/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/hyb/workspaces/hexo/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper [as partial] (/home/hyb/workspaces/hexo/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at compile (/home/hyb/workspaces/hexo/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:43:17)
    at returnedFn (/home/hyb/workspaces/hexo/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiled (/home/hyb/workspaces/hexo/node_modules/hexo/lib/theme/view.js:127:30)
    at Theme._View.View.View.render (/home/hyb/workspaces/hexo/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/hyb/workspaces/hexo/node_modules/hexo/lib/hexo/index.js:390:25
    at tryCatcher (/home/hyb/workspaces/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /home/hyb/workspaces/hexo/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/hyb/workspaces/hexo/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:445:10)
    at resume_ (_stream_readable.js:825:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```
hexo 版本3.3.9
难道是因为版本太老？
