### ISSUE TITLE
hexo g 报错

### ISSUE THREAD

**Issue by toughChow** [shenliyang/hexo-theme-snippet#143]
请问这个什么原因导致的错误呀，在**hexo g**的时候生成的 
```
PS D:\1-My\Workspace\github\hexo-tmp> hexo g
INFO  =========================================
INFO    Welcome to use Snippet theme for hexo
INFO  =========================================
INFO  Start processing
INFO  Files loaded in 2.31 s
ERROR D:\1-My\Workspace\github\hexo-tmp\themes\hexo-theme-snippet\layout\layout.ejs:5
    3|   <div id="container">
    4|     <div id="wrap">
 >> 5|       <%- partial('_partial/header', null, {cache: !config.relative_link}) %>
    6|       <div class="outer">
    7|         <section id="main"><%- body %></section>
    8|         <% if (theme.sidebar && theme.sidebar !== 'bottom'){ %>

D:\1-My\Workspace\github\hexo-tmp\themes\hexo-theme-snippet\layout\_partial\header.ejs:18
    16|         <a id="main-nav-toggle" class="nav-icon"></a>
    17|         <% for (var i in theme.menu){ %>
 >> 18|           <a class="main-nav-link" href="<%- url_for(theme.menu[i]) %>"><%= i %></a>
    19|         <% } %>
    20|       </nav>
    21|       <nav id="sub-nav">

path.startsWith is not a function
TypeError: D:\1-My\Workspace\github\hexo-tmp\themes\hexo-theme-snippet\layout\layout.ejs:5
    3|   <div id="container">
    4|     <div id="wrap">
 >> 5|       <%- partial('_partial/header', null, {cache: !config.relative_link}) %>
    6|       <div class="outer">
    7|         <section id="main"><%- body %></section>
    8|         <% if (theme.sidebar && theme.sidebar !== 'bottom'){ %>

D:\1-My\Workspace\github\hexo-tmp\themes\hexo-theme-snippet\layout\_partial\header.ejs:18
    16|         <a id="main-nav-toggle" class="nav-icon"></a>
    17|         <% for (var i in theme.menu){ %>
 >> 18|           <a class="main-nav-link" href="<%- url_for(theme.menu[i]) %>"><%= i %></a>
    19|         <% } %>
    20|       </nav>
    21|       <nav id="sub-nav">

path.startsWith is not a function
    at Object.urlForHelper (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\plugins\helper\url_for.js:6:31)
    at eval (eval at compile (D:\1-My\Workspace\github\hexo-tmp\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:30:17)
    at returnedFn (D:\1-My\Workspace\github\hexo-tmp\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\theme\view.js:49:23)
    at fragment_cache (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\plugins\helper\partial.js:35:52)
    at Object.fragmentCache (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\plugins\helper\fragment_cache.js:9:32)
    at Object.partial (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\plugins\helper\partial.js:35:17)
    at eval (eval at compile (D:\1-My\Workspace\github\hexo-tmp\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:12:17)
    at returnedFn (D:\1-My\Workspace\github\hexo-tmp\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\theme\view.js:30:15)
    at _compiled.then.result (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\theme\view.js:41:23)
    at tryCatcher (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\promise.js:699:18)
    at _drainQueueStep (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\async.js:17:14)
ERROR D:\1-My\Workspace\github\hexo-tmp\themes\hexo-theme-snippet\layout\layout.ejs:5
    3|   <div id="container">
    4|     <div id="wrap">
 >> 5|       <%- partial('_partial/header', null, {cache: !config.relative_link}) %>
    6|       <div class="outer">
    7|         <section id="main"><%- body %></section>
    8|         <% if (theme.sidebar && theme.sidebar !== 'bottom'){ %>

D:\1-My\Workspace\github\hexo-tmp\themes\hexo-theme-snippet\layout\_partial\header.ejs:18
    16|         <a id="main-nav-toggle" class="nav-icon"></a>
    17|         <% for (var i in theme.menu){ %>
 >> 18|           <a class="main-nav-link" href="<%- url_for(theme.menu[i]) %>"><%= i %></a>
    19|         <% } %>
    20|       </nav>
    21|       <nav id="sub-nav">

path.startsWith is not a function
TypeError: D:\1-My\Workspace\github\hexo-tmp\themes\hexo-theme-snippet\layout\layout.ejs:5
    3|   <div id="container">
    4|     <div id="wrap">
 >> 5|       <%- partial('_partial/header', null, {cache: !config.relative_link}) %>
    6|       <div class="outer">
    7|         <section id="main"><%- body %></section>
    8|         <% if (theme.sidebar && theme.sidebar !== 'bottom'){ %>

D:\1-My\Workspace\github\hexo-tmp\themes\hexo-theme-snippet\layout\_partial\header.ejs:18
    16|         <a id="main-nav-toggle" class="nav-icon"></a>
    17|         <% for (var i in theme.menu){ %>
 >> 18|           <a class="main-nav-link" href="<%- url_for(theme.menu[i]) %>"><%= i %></a>
    19|         <% } %>
    20|       </nav>
    21|       <nav id="sub-nav">

path.startsWith is not a function
    at Object.urlForHelper (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\plugins\helper\url_for.js:6:31)
    at eval (eval at compile (D:\1-My\Workspace\github\hexo-tmp\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:30:17)
    at returnedFn (D:\1-My\Workspace\github\hexo-tmp\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\theme\view.js:49:23)
    at fragment_cache (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\plugins\helper\partial.js:35:52)
    at Object.fragmentCache (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\plugins\helper\fragment_cache.js:9:32)
    at Object.partial (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\plugins\helper\partial.js:35:17)
    at eval (eval at compile (D:\1-My\Workspace\github\hexo-tmp\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:12:17)
    at returnedFn (D:\1-My\Workspace\github\hexo-tmp\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\theme\view.js:30:15)
    at _compiled.then.result (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\theme\view.js:41:23)
    at tryCatcher (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\promise.js:699:18)
    at _drainQueueStep (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\async.js:17:14)
ERROR D:\1-My\Workspace\github\hexo-tmp\themes\hexo-theme-snippet\layout\layout.ejs:5
    3|   <div id="container">
    4|     <div id="wrap">
 >> 5|       <%- partial('_partial/header', null, {cache: !config.relative_link}) %>
    6|       <div class="outer">
    7|         <section id="main"><%- body %></section>
    8|         <% if (theme.sidebar && theme.sidebar !== 'bottom'){ %>

D:\1-My\Workspace\github\hexo-tmp\themes\hexo-theme-snippet\layout\_partial\header.ejs:18
    16|         <a id="main-nav-toggle" class="nav-icon"></a>
    17|         <% for (var i in theme.menu){ %>
 >> 18|           <a class="main-nav-link" href="<%- url_for(theme.menu[i]) %>"><%= i %></a>
    19|         <% } %>
    20|       </nav>
    21|       <nav id="sub-nav">

path.startsWith is not a function
TypeError: D:\1-My\Workspace\github\hexo-tmp\themes\hexo-theme-snippet\layout\layout.ejs:5
    3|   <div id="container">
    4|     <div id="wrap">
 >> 5|       <%- partial('_partial/header', null, {cache: !config.relative_link}) %>
    6|       <div class="outer">
    7|         <section id="main"><%- body %></section>
    8|         <% if (theme.sidebar && theme.sidebar !== 'bottom'){ %>

D:\1-My\Workspace\github\hexo-tmp\themes\hexo-theme-snippet\layout\_partial\header.ejs:18
    16|         <a id="main-nav-toggle" class="nav-icon"></a>
    17|         <% for (var i in theme.menu){ %>
 >> 18|           <a class="main-nav-link" href="<%- url_for(theme.menu[i]) %>"><%= i %></a>
    19|         <% } %>
    20|       </nav>
    21|       <nav id="sub-nav">

path.startsWith is not a function
    at Object.urlForHelper (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\plugins\helper\url_for.js:6:31)
    at eval (eval at compile (D:\1-My\Workspace\github\hexo-tmp\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:30:17)
    at returnedFn (D:\1-My\Workspace\github\hexo-tmp\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\theme\view.js:49:23)
    at fragment_cache (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\plugins\helper\partial.js:35:52)
    at Object.fragmentCache (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\plugins\helper\fragment_cache.js:9:32)
    at Object.partial (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\plugins\helper\partial.js:35:17)
    at eval (eval at compile (D:\1-My\Workspace\github\hexo-tmp\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:12:17)
    at returnedFn (D:\1-My\Workspace\github\hexo-tmp\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\theme\view.js:30:15)
    at _compiled.then.result (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\theme\view.js:41:23)
    at tryCatcher (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\promise.js:699:18)
    at _drainQueueStep (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\async.js:17:14)
ERROR D:\1-My\Workspace\github\hexo-tmp\themes\hexo-theme-snippet\layout\layout.ejs:5
    3|   <div id="container">
    4|     <div id="wrap">
 >> 5|       <%- partial('_partial/header', null, {cache: !config.relative_link}) %>
    6|       <div class="outer">
    7|         <section id="main"><%- body %></section>
    8|         <% if (theme.sidebar && theme.sidebar !== 'bottom'){ %>

D:\1-My\Workspace\github\hexo-tmp\themes\hexo-theme-snippet\layout\_partial\header.ejs:18
    16|         <a id="main-nav-toggle" class="nav-icon"></a>
    17|         <% for (var i in theme.menu){ %>
 >> 18|           <a class="main-nav-link" href="<%- url_for(theme.menu[i]) %>"><%= i %></a>
    19|         <% } %>
    20|       </nav>
    21|       <nav id="sub-nav">

path.startsWith is not a function
TypeError: D:\1-My\Workspace\github\hexo-tmp\themes\hexo-theme-snippet\layout\layout.ejs:5
    3|   <div id="container">
    4|     <div id="wrap">
 >> 5|       <%- partial('_partial/header', null, {cache: !config.relative_link}) %>
    6|       <div class="outer">
    7|         <section id="main"><%- body %></section>
    8|         <% if (theme.sidebar && theme.sidebar !== 'bottom'){ %>

D:\1-My\Workspace\github\hexo-tmp\themes\hexo-theme-snippet\layout\_partial\header.ejs:18
    16|         <a id="main-nav-toggle" class="nav-icon"></a>
    17|         <% for (var i in theme.menu){ %>
 >> 18|           <a class="main-nav-link" href="<%- url_for(theme.menu[i]) %>"><%= i %></a>
    19|         <% } %>
    20|       </nav>
    21|       <nav id="sub-nav">

path.startsWith is not a function
    at Object.urlForHelper (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\plugins\helper\url_for.js:6:31)
    at eval (eval at compile (D:\1-My\Workspace\github\hexo-tmp\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:30:17)
    at returnedFn (D:\1-My\Workspace\github\hexo-tmp\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\theme\view.js:49:23)
    at fragment_cache (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\plugins\helper\partial.js:35:52)
    at Object.fragmentCache (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\plugins\helper\fragment_cache.js:9:32)
    at Object.partial (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\plugins\helper\partial.js:35:17)
    at eval (eval at compile (D:\1-My\Workspace\github\hexo-tmp\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:12:17)
    at returnedFn (D:\1-My\Workspace\github\hexo-tmp\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\theme\view.js:30:15)
    at _compiled.then.result (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\theme\view.js:41:23)
    at tryCatcher (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\promise.js:699:18)
    at _drainQueueStep (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\async.js:17:14)
ERROR D:\1-My\Workspace\github\hexo-tmp\themes\hexo-theme-snippet\layout\layout.ejs:5
    3|   <div id="container">
    4|     <div id="wrap">
 >> 5|       <%- partial('_partial/header', null, {cache: !config.relative_link}) %>
    6|       <div class="outer">
    7|         <section id="main"><%- body %></section>
    8|         <% if (theme.sidebar && theme.sidebar !== 'bottom'){ %>

D:\1-My\Workspace\github\hexo-tmp\themes\hexo-theme-snippet\layout\_partial\header.ejs:18
    16|         <a id="main-nav-toggle" class="nav-icon"></a>
    17|         <% for (var i in theme.menu){ %>
 >> 18|           <a class="main-nav-link" href="<%- url_for(theme.menu[i]) %>"><%= i %></a>
    19|         <% } %>
    20|       </nav>
    21|       <nav id="sub-nav">

path.startsWith is not a function
TypeError: D:\1-My\Workspace\github\hexo-tmp\themes\hexo-theme-snippet\layout\layout.ejs:5
    3|   <div id="container">
    4|     <div id="wrap">
 >> 5|       <%- partial('_partial/header', null, {cache: !config.relative_link}) %>
    6|       <div class="outer">
    7|         <section id="main"><%- body %></section>
    8|         <% if (theme.sidebar && theme.sidebar !== 'bottom'){ %>

D:\1-My\Workspace\github\hexo-tmp\themes\hexo-theme-snippet\layout\_partial\header.ejs:18
    16|         <a id="main-nav-toggle" class="nav-icon"></a>
    17|         <% for (var i in theme.menu){ %>
 >> 18|           <a class="main-nav-link" href="<%- url_for(theme.menu[i]) %>"><%= i %></a>
    19|         <% } %>
    20|       </nav>
    21|       <nav id="sub-nav">

path.startsWith is not a function
    at Object.urlForHelper (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\plugins\helper\url_for.js:6:31)
    at eval (eval at compile (D:\1-My\Workspace\github\hexo-tmp\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:30:17)
    at returnedFn (D:\1-My\Workspace\github\hexo-tmp\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\theme\view.js:49:23)
    at fragment_cache (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\plugins\helper\partial.js:35:52)
    at Object.fragmentCache (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\plugins\helper\fragment_cache.js:9:32)
    at Object.partial (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\plugins\helper\partial.js:35:17)
    at eval (eval at compile (D:\1-My\Workspace\github\hexo-tmp\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:12:17)
    at returnedFn (D:\1-My\Workspace\github\hexo-tmp\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\theme\view.js:30:15)
    at _compiled.then.result (D:\1-My\Workspace\github\hexo-tmp\node_modules\hexo\lib\theme\view.js:41:23)
    at tryCatcher (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\promise.js:699:18)
    at _drainQueueStep (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\1-My\Workspace\github\hexo-tmp\node_modules\bluebird\js\release\async.js:17:14)
```

**Comment by shenliyang** [comment]
您好，请先检查菜单配置。

**Comment by toughChow** [comment]
> 您好，请先检查菜单配置。

这个问题解决了，是不能使用hexo自带的_config.yml 使用了主题内部的配置文件就好勒。
但是现在出现了 
```
no layout: index.html
```
这个问题，我是前端小白一个哈哈哈还劳烦多指教

**Comment by toughChow** [comment]
大致找到原因了，只要配置在_config.yml中配置菜单 然后执行 `hexo g` 就会报错。
请问菜单目录是创建在hexo下的sources还是 theme下的sources呀？ 我两种方式的尝试了都不行

**Comment by toughChow** [comment]
大哥 搞起了，之前用的是next主题，然后切换出了问题。现在初始化了一个项目，就ok了。感谢！
