### ISSUE TITLE
can not read a block mapping entry; a multiline key may not be an implicit key at line 2, column 5:

### ISSUE THREAD

**Issue by s2339956** [shenliyang/hexo-theme-snippet#170]
> 请先确认以下情况：
- [Ｏ] 拉取主题最新代码，问题依然存在。
- [Ｏ] 已经搜索Issues历史记录，并阅读过：[主题常见问题](https://github.com/shenliyang/hexo-theme-snippet#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [Ｏ] 提Issues前建议先阅读：[《你不知道的提Issues技巧》](https://github.com/shenliyang/hexo-theme-snippet#你不知道的提Issues技巧)

> 为了能精准定位问题，希望尽量提供一下信息
1. 相关问题截图
2. 有线上环境，建议提供一下网址
3. 如果是兼容bug，建议提供下设备型号，浏览器名称及版本

------- **如果是意见或建议，可以忽略以内容** ------------

Error log:

YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 2, column 5:
    date: 2020-07-13 10:39:38
        ^
    at generateError (/Users/tinxie/Documents/hexo/blog/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/Users/tinxie/Documents/hexo/blog/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at readBlockMapping (/Users/tinxie/Documents/hexo/blog/node_modules/js-yaml/lib/js-yaml/loader.js:1073:9)
    at composeNode (/Users/tinxie/Documents/hexo/blog/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (/Users/tinxie/Documents/hexo/blog/node_modules/js-yaml/lib/js-yaml/loader.js:1519:3)
    at loadDocuments (/Users/tinxie/Documents/hexo/blog/node_modules/js-yaml/lib/js-yaml/loader.js:1575:5)
    at Object.load (/Users/tinxie/Documents/hexo/blog/node_modules/js-yaml/lib/js-yaml/loader.js:1596:19)
    at parseYAML (/Users/tinxie/Documents/hexo/blog/node_modules/hexo-front-matter/lib/front_matter.js:78:23)
    at parse (/Users/tinxie/Documents/hexo/blog/node_modules/hexo-front-matter/lib/front_matter.js:54:12)
    at /Users/tinxie/Documents/hexo/blog/node_modules/hexo/lib/plugins/processor/post.js:48:20
    at tryCatcher (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:544:35)
    at Promise._settlePromise (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:673:18)
    at PromiseArray._resolve (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/promise_array.js:145:14)
    at PromiseArray._iterate (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/promise_array.js:115:31)
    at PromiseArray.init [as _init] (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/promise_array.js:79:10)
    at Promise._settlePromise (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:601:21)
    at Promise._settlePromise0 (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:673:18)
    at PromiseArray._resolve (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/promise_array.js:145:14)
    at Promise._settlePromise (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:609:26)
    at Promise._settlePromise0 (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:673:18)
    at /Users/tinxie/Documents/hexo/blog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/tinxie/Documents/hexo/blog/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)

title: [轉]IDA Pro demo 
date: 2020-07-13 10:39:38
categories: [macOS] 
tags: [macOS]       
comments: true 
img:

**Comment by s2339956** [comment]
使用 [ ] 會報錯
title: [轉] IDA Pro 7.3 
date: 2020-08-07 17:10:50
```
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 2, column 5:
    date: 2020-08-07 17:10:50
```
使用 ( ) 正常
title: (轉) IDA Pro 7.3 
date: 2020-08-07 17:10:50

**Comment by shenliyang** [comment]
请提供配置和hexo版本
